### ISSUE TITLE
"so," isn't highlighted correctly

### ISSUE THREAD

**Issue by jesstelford** [Pamplemousse/badWords#3]
I'm not sure why (my vimscript-fu isn't very strong).

<img width="662" alt="screen shot 2018-05-17 at 9 03 03 am" src="https://user-images.githubusercontent.com/612020/40148413-357fedb8-59b1-11e8-9ca1-a3764d6c1b5b.png">

In this variant, it doesn't highlight either, so perhaps there's something significant about the comma?

```vim
highlight badWords ctermbg=red ctermfg=white
fun! HiBadWords()
  match badWords /\c\<\(obviously\|basically\|simply\|of\scourse\|clearly\|just\|everyone\sknows\|however\|so,\|easy\)\>/
endfun
autocmd InsertEnter *.md call HiBadWords()
autocmd InsertLeave *.md call HiBadWords()
```

**Comment by Pamplemousse** [comment]
I think it behave this way because `\<` and `\>` are used in the regex to catch whole words ([relevant doc](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/\%3C)) and I guess ',' cannot be part of a word.

If I change that, for example replacing in [badWords.vim#L19](https://github.com/Pamplemousse/badWords/blob/master/plugin/badWords.vim#L19)
```
let matcher='\c\<\(' . join(lang, '\|') . '\)\>'
```
by
```
let matcher='\c\(' . join(lang, '\|') . '\)'
```

then, there is a side effect: `trivially` will then only be partially highlighted (the `trivial` part of it).

---

Aside from the technical challenge, I thought about `so,` not being too much of a bad word (in a sense that it won't make beginners feel embarrassed), and I feel that it should be treated the same way I treated `however` : by removing it.

What do you think?

**Comment by Pamplemousse** [comment]
Thanks for your input.

Removed it in ad829aa then.
